apiVersion: v1
kind: Service
metadata:
  name: squid
  labels:
    name: squid
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3128
      protocol: TCP
  selector:
    name: squid
